server:
  port: 8088
  #在propertis配置文件中加上这两行即可放开拦截:
  error:
    include-exception: true
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.30.2.60:3306/test_maxwell?serverTimezone=GMT%2b8
    username: root
    password: 123456
  ##测试环境

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true

mybatis:
  config-location: classpath:mybatis-config
  mapper-locations: classpath:mappers/*
  type-aliases-package: com.akisan.akiblog.entity

mybatis-plus:
  mapper-locations:
    - classpath:mappers/*
  #实体类别名配置
  type-aliases-package: com.akisan.akiblog.entity
  #日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl